name: Build code-server-pytorch image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/codeserver-pytorch-ci.yml'
      - 'codeserver-pytorch/**'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/codeserver-pytorch-ci.yml'
      - 'codeserver-pytorch/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@879dcbb708d40f8b8679d4f7941b938a086e23a7
        with:
          images: zjuici/codeserver
          flavor: |
            prefix=pytorch-
      - name: Build Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: codeserver-pytorch/Dockerfile
          context: codeserver-pytorch
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
