name: Build code-server image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/codeserver-ci.yml'
      - 'codeserver/**'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/codeserver-ci.yml'
      - 'codeserver/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: zjuici/codeserver
      - name: Build Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          file: codeserver/Dockerfile
          context: codeserver
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
