name: Build jupyter-pandas image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/jupyter-pandas-ci.yml'
      - 'jupyter-pandas/**'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/jupyter-pandas-ci.yml'
      - 'jupyter-pandas/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@879dcbb708d40f8b8679d4f7941b938a086e23a7
        with:
          images: zjuici/jupyter
          flavor: |
            prefix=pandas-
      - name: Build Docker image
        uses: docker/build-push-action@fdf7f43ecf7c1a5c7afe936410233728a8c2d9c2
        with:
          file: jupyter-pandas/Dockerfile
          context: jupyter-pandas
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
